# Generated by Django 4.1.2 on 2023-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_point_pointhistory_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='eth_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='xml_balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, default=None),
        ),
    ]
