# Generated by Django 4.1.2 on 2023-01-10 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_eth_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 11, 7, 14, 23, 421773)),
        ),
    ]
