# Generated by Django 4.1.2 on 2023-01-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pub_date',
        ),
    ]
